
services:
  - type: web
    name: levi-multi-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
