services:
  - type: web
    name: levi-multi-bot
    env: python
    plan: standard
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT1_TOKEN
        value: YOUR_BOT1_TOKEN
      - key: ADMIN_ID
        value: "123456789"
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 1
