
services:
  - type: web
    name: levi-multi-bot
    env: python
    plan: standard
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: ADMIN_ID
        value: "123456789"
      - key: SHARE_API_URL
        value: "https://example.com"
    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
