services:
  - type: web
    name: levi-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

  - type: worker
    name: telegram-bots
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: standard
    disk:
      name: bot-persistent-storage
      mountPath: /mnt/data
      sizeGB: 1
